# Generated by Django 4.2.8 on 2024-02-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title of the vacancy')),
                ('salary_from', models.PositiveSmallIntegerField(verbose_name='Salary starts form (USD)')),
                ('salary_to', models.PositiveSmallIntegerField(verbose_name='Salary ends in (USD)')),
                ('description', models.TextField(verbose_name='Description of the vacancy')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Vacancy publication date')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer.employer', verbose_name='Company')),
                ('required_skills', models.ManyToManyField(to='employee.employeeskill', verbose_name='Required skills')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
