# Generated by Django 4.2.8 on 2024-02-29 15:56

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128, verbose_name='Fullname')),
                ('about', models.TextField(verbose_name='About the employee')),
                ('experience', models.PositiveSmallIntegerField(verbose_name='Experience in years')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number', models.CharField(max_length=13)),
                ('photo', image_optimizer.fields.OptimizedImageField(upload_to='employee_photos', verbose_name='Employee Photo')),
                ('skills', models.ManyToManyField(to='employee.employeeskill', verbose_name='skills')),
            ],
        ),
    ]
